### ISSUE TITLE
25/03 Introducción a la programación

### ISSUE THREAD

**Issue by AlexS12** [AeroPython/Curso_AeroPython#70]
Introducción a la programación.

No habrá muchos detalles sobre qué es Python, sus características, cómo se instala... sino que nos pondremos manos a la obra directamente. Los detalles de Python quedan para la segunda clase.

Notebooks:

- [x] 002-Sintaxis_basica_i_tipos_datos.ipynb (@mabeldelgadob)
- [x] 002b-Sintaxis_basica_ii_utilizando_librerias.ipynb (@mabeldelgadob)
- [x] 003-Sintaxis_basica_iii_funciones.ipynb (@mabeldelgadob)
- [x] 003b-Sintaxis_basica_iv_estructuras_control.ipynb (@mabeldelgadob)	
- [x] 004-PythonBasico-EjerciciosBuclesCond... con añadidos de Pyladies (@leonardotodisco)

**Comment by leonardotodisco** [comment]
004-PythonBasico-EjerciciosBuclesCond... con añadidos de Pyladie (Leo)

**Comment by AlexS12** [comment]
Hola @leonardotodisco ¿vas a hacer algún cambio en los ejercicios? si necesitas ayuda, dínoslo por aquí =)
