### ISSUE TITLE
28/03 NumPy

### ISSUE THREAD

**Issue by AlexS12** [AeroPython/Curso_AeroPython#72]
- [ ] 010-NumPy-Intro.ipynb (~~@JMSH87~~)  (@martosc)
- [ ] 011-NumPy-CaracteristicasArrays.ipynb / 012-NumPy-Importacion.ipynb ¿? (~~@JMSH87~~)  (@martosc)
- [ ] 013-NumPy-SeccionesArrays.ipynb (~~@JMSH87~~) (@martosc)
- [ ] 014-NumPy-AlgerbraLineal.ipynb (@AlexS12  )
- [ ] 015-NumPy-EntradaSalida.ipynb (@AlexS12 )

**Comment by leonardotodisco** [comment]
010-NumPy-Intro.ipynb (JM)
 011-NumPy-CaracteristicasArrays.ipynb (JM)
012-NumPy-Importacion.ipynb (JM)

**Comment by AlexS12** [comment]
@martosc ¿puedes confirmar que vienes este día y te encargas de los notebooks de arriba?

**Comment by martosc** [comment]
Confirmado, el 28 me encargo yo de estos tres primeros notebooks.

**Comment by AlexS12** [comment]
Queda pendiente entrada y salida, que pasa a la siguiente clase
