### ISSUE TITLE
01/04 matplotlib / scipy.integrate

### ISSUE THREAD

**Issue by AlexS12** [AeroPython/Curso_AeroPython#73]
- [ ] 020-matplotlib-Intro.ipynb (@leonardotodisco)
- [ ] 021-matplotlib-widgets.ipynb (@leonardotodisco)
- [ ] 031-SciPy-CalculoIntegrales.ipynb

**Comment by leonardotodisco** [comment]
020-matplotlib-Intro.ipynb (Leo)
 021-matplotlib-widgets.ipynb (Leo)

**Comment by AlexS12** [comment]
015-NumPy-EntradaSalida.ipynb Pendiente de la clase anterior
