### ISSUE TITLE
NEW notebook: scipy.signal 

### ISSUE THREAD

**Issue by AlexS12** [AeroPython/Curso_AeroPython#77]
Adaptación de MATLAB de Jose Manuel Soria

**Comment by AlexS12** [comment]
@JMSH87, hablamos por aquí si te parece para ir incluyendo el notebook. He intentado echarle un vistazo esta tarde, pero no tengo el fichero de datos. 

Creo, por lo que he visto que no va a haber problemas en adaptarlo con lo que hay por aquí:
https://docs.scipy.org/doc/scipy-0.18.1/reference/signal.html
https://docs.scipy.org/doc/scipy-0.18.1/reference/generated/scipy.signal.csd.html

Esta semana buscamos un día para sentarnos juntos en cualquier caso

**Comment by JMSH87** [comment]
De acuerdo Álex!

**Comment by martosc** [comment]
De cara a cerrar este issue, está el codigo Matlab subido en algún sitio?

**Comment by AlexS12** [comment]
Yo lo cerraría directamente. Si en algún momento retomamos el tema de análisis de señal, podemos buscar material.
