### ISSUE TITLE
Reparto clases curso URJC Octubre 2019

### ISSUE THREAD

**Issue by martosc** [AeroPython/Curso_AeroPython#84]
Abro este issue para repartirnos clases y notebooks:

| Día  | Notebook | Persona encargada | Comentario |
| ------------- | ------------- | -| -| 
| 7 Octubre Primera parte | 000-Bienvenido.ipynb   001-PythonBasico-JupyterNotebook.ipynb  | - | @AlexS12 no puede |
| 7 Octubre Segunda parte  | 002-Sintaxis_basica_i_tipos_datos.ipynb   002b-Sintaxis_basica_ii_utilizando_librerias.ipynb	  | - | -| 
| 10 Octubre Primera parte  | 003-Sintaxis_basica_iii_funciones.ipynb  003b-Sintaxis_basica_iv_estructuras_control.ipynb	 | - | -| 
| 10 Octubre Segunda parte  | 010-NumPy-Intro.ipynb  | - | -| 
| 14 Octubre Primera parte  | 011-NumPy-CaracteristicasArrays.ipynb 012-NumPy-Importacion.ipynb  | - | Vlad sí puede| 
| 14 Octubre Segunda parte  | 013-NumPy-SeccionesArrays.ipynb   | - | @AlexS12 no puede; Vlad sí puede | 
| 17 Octubre Primera parte  | 14-NumPy-AlgerbraLineal.ipynb  | - | Vlad sí puede| 
| 17 Octubre Segunda parte  | 020-matplotlib-Intro.ipynb  | - | Vlad sí puede| 
| 21 Octubre Primera parte  | 030-SciPy-FuncionesEspeciales.ipynb  | - |  @martosc no puede asistir, @AlexS12 no puede; Vlad sí puede|  
| 21 Octubre Segunda parte  | 031-SciPy-CalculoIntegrales.ipynb  | - | @martosc no puede asistir, Vlad sí puede| 
| 24 Octubre Primera parte  | 040-SymPy-Intro.ipynb  | - | -| 
| 24 Octubre Segunda parte  | 050-Pandas-Intro.ipynb  | - | -|

**Comment by AlexS12** [comment]
Con respecto al temario:

- Creo que el dia 14 da tiempo a terminar numpy incluyendo álgebra lineal. (podemos dejar entrada-salida a trabajar por cuenta propia)
- El 17 podemos hacer matplotlib con widgets e integrales
- El 21 interpolación, ajuste y funciones especiales:
  - funciones especiales tiene poca cosa y se puede trabajar por cuenta propia creo yo.
- El 24 yo haría EDOs y Sympy

Hay que tener en cuenta que comprometimos que era un curso de Python orientado a temas de numérico, o sea que no podemos dejar fuera tanto de scipy (desde mi punto de vista)

Pandas es jugoso, pero sólo veo opción de meterlo si quitamos sympy, pero suele ser una de las cosas que más les gusta. Mi opción sería hacer un curso entero (quizá más corto) de datos todo... 

@martos, @mabel, si os parece bien lo que pongo arriba, actualizamos la tabla y ponemos de qué queremos encargarnos dentro de la disponibilidad que tenemos.

**Comment by AlexS12** [comment]
Ping

**Comment by mabeldelgadob** [comment]
Actualizo la tabla con como creo que deberían ser las clases e integrando los comentarios de @AlexS12. 

Mañana lunes arrancamos @martosc  y yo, y en cuanto a mi disponibilidad, como es comenté, sólo puedo un día a la semana.

| Día  | Notebook | Persona encargada | Comentario |
| ------------- | ------------- | -| -| 
| 7 Octubre Primera parte | 000-Bienvenido.ipynb   001-PythonBasico-JupyterNotebook.ipynb  002-PythonBasico-TiposDeDatos.ipynb | - | @AlexS12 no puede |
| 7 Octubre Segunda parte  |  003-PythonBasico-EstructurasDeControl 004-PythonBasicoFunciones   Dejamos el notebook 005-PythonBasico-EjerciciosBuclesCondicionales para casa| - | -| 
| 10 Octubre Primera parte  | 	010-NumPy-Intro.ipynb  011-NumPy-CaracteristicasArrays  | - | -| 
| 10 Octubre Segunda parte  | 012-NumPy-Importacion 013-NumPy-SeccionesArrays   | - | -| 
| 14 Octubre Primera parte  | 014-NumPy-AlgebraLineal  | - | Vlad sí puede| 
| 14 Octubre Segunda parte  | 015-NumPy-EntradaSalida  | - | @AlexS12 no puede; Vlad sí puede | 
| 17 Octubre Primera parte  | 020-matplotlib-Intro.ipynb  | - | Vlad sí puede.| 
| 17 Octubre Segunda parte  | 021-matplotlib-widgets.ipynb | - | Vlad sí puede| 
| 21 Octubre Primera parte  | 030-SciPy-FuncionesEspeciales.ipynb  031-SciPy-CalculosIntegrales.ipynb| - |  @martosc no puede asistir, @AlexS12 no puede; Vlad sí puede|  
| 21 Octubre Segunda parte  | 033-SciPy-InterpolacionAjuste.ipynb  034-SciPy-EcuacionesNoLineales (si diese tiempo)| - | @martosc no puede asistir, Vlad sí puede| 
| 24 Octubre Primera parte  |  035-SciPy-EcuacionesDiferencialesOrdinarias | - | -| 
| 24 Octubre Segunda parte  | 040-SymPy-Intro.ipynb  | - | -|

**Comment by martosc** [comment]
Actualizo la tabla a día 12 de Octubre:
Abro este issue para repartirnos clases y notebooks:

| Día  | Notebook | Persona encargada | Comentario |
| ------------- | ------------- | -| -| 
| 7 Octubre Primera parte | 000-Bienvenido.ipynb   001-PythonBasico-JupyterNotebook.ipynb  | @mabeldelgadob  | @AlexS12 no puede |
| 7 Octubre Segunda parte  | 002-Sintaxis_basica_i_tipos_datos.ipynb   002b-Sintaxis_basica_ii_utilizando_librerias.ipynb	  | - | -| 
| 10 Octubre Primera parte  | 003-Sintaxis_basica_iii_funciones.ipynb  003b-Sintaxis_basica_iv_estructuras_control.ipynb	 | - | -| 
| 10 Octubre Segunda parte  | 010-NumPy-Intro.ipynb  | @martosc  | -| 
| 14 Octubre Primera parte  | 011-NumPy-CaracteristicasArrays.ipynb 012-NumPy-Importacion.ipynb  | - | Vlad sí puede| 
| 14 Octubre Segunda parte  | 14-NumPy-AlgerbraLineal.ipynb   | - | @AlexS12 no puede; Vlad sí puede | 
| 17 Octubre Primera parte  | 013-NumPy-SeccionesArrays.ipynb   | - | Vlad sí puede| 
| 17 Octubre Segunda parte  | 020-matplotlib-Intro.ipynb  | - | Vlad sí puede| 
| 21 Octubre Primera parte  | 030-SciPy-FuncionesEspeciales.ipynb  | - |  @martosc no puede asistir, @AlexS12 no puede; Vlad sí puede|  
| 21 Octubre Segunda parte  | 031-SciPy-CalculoIntegrales.ipynb  | - | @martosc no puede asistir, Vlad sí puede| 
| 24 Octubre Primera parte  | 040-SymPy-Intro.ipynb  | - | -| 
| 24 Octubre Segunda parte  | 050-Pandas-Intro.ipynb  | - | -|
