### ISSUE TITLE
Enlace a introducción roto

### ISSUE THREAD

**Issue by astrojuanlu** [AeroPython/Curso_AeroPython#85]
Nos avisa @olrosales (¡gracias!) de que el enlace a la introducción en el README está roto. El enlace correcto ahora es este:

https://github.com/AeroPython/Curso_AeroPython/blob/master/notebooks_completos/000-Bienvenido.ipynb

¿Alguien se anima a cambiarlo?

**Comment by martosc** [comment]
Cambiado, falta review y mergeado.
